ALTER TABLE `Fund`
  ADD COLUMN `takeProfitTrigger` DECIMAL(5, 2) NOT NULL DEFAULT 8.00,
  ADD COLUMN `takeProfitDrawdown` DECIMAL(5, 2) NOT NULL DEFAULT 3.00,
  ADD COLUMN `takeProfitSellPercent` DECIMAL(5, 2) NOT NULL DEFAULT 50.00;
